baseURL = "https://www.gnblilnk.dev/"
title = "ğŸ‘¾ Gina's Tech Blog"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"


[pagination]
pagerSize = 20

[services]
[services.disqus]
shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Gina Xu"
  info = "I build things for Web & Mobile"
  description = "John Doe's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "https://www.shutgnblink.blog/img/avatar_hu7331c604e51c27b6e5cfc85d6dac2614_113250_300x0_resize_box_3.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

 # since = 2024

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  customCSS = []
  # customSCSS = ["scss/custom.scss"]
  customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Gnblink0"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/gina-shiyu-xu/"



# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"


[languages]
  [languages.en]
    languageName = "ğŸ‡¨ğŸ‡¦"
    weight = 1
    title = "ğŸ‘¾ Gina's Tech Blog"
    description = "A tech blog by Gina Xu on Web & Mobile development"
    keywords = "blog, developer, web, mobile, tech"
  
    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"

    [[languages.en.menu.main]]
      name = "Blog"
      weight = 2
      url = "posts/"

    [[languages.en.menu.main]]
      name = "Projects"
      weight = 3
      url = "projects/"

    [[languages.en.menu.main]]
      name = "Contact me"
      weight = 5
      url = "contact/"

  [languages.zh]
    languageName = ":cn:"
    weight = 2
    title = "ğŸ‘¾ Ginaçš„æŠ€æœ¯åšå®¢"
    description = "Gina Xuçš„Webä¸ç§»åŠ¨å¼€å‘æŠ€æœ¯åšå®¢"
    keywords = "åšå®¢, å¼€å‘è€…, Web, ç§»åŠ¨, æŠ€æœ¯"

    [[languages.zh.menu.main]]
      name = "å…³äº"
      weight = 1
      url = "about/"

    [[languages.zh.menu.main]]
      name = "åšå®¢"
      weight = 2
      url = "posts/"

    [[languages.zh.menu.main]]
      name = "é¡¹ç›®"
      weight = 3
      url = "projects/"

    [[languages.zh.menu.main]]
      name = "è”ç³»æˆ‘"
      weight = 5
      url = "contact/"
